"""Deterministic renderers for the two generated parking views (v24.0.0).

Both renderers are pure functions of a :class:`ParkingSnapshot`. That is what
makes drift detectable: the lint pass re-renders from the ledgers and compares
byte for byte, so a hand edit to either view is caught rather than silently
becoming a second source of truth.
"""

from __future__ import annotations

from devolaflow.parking.models import (
    JUDGE_VIEW_MARKER,
    RISK_INDEX_MARKER,
    ParkingSnapshot,
    RiskState,
    Severity,
)
from devolaflow.workspace_ledger import render_rows_table

_SEVERITY_ORDER = {
    Severity.BLOCKER: 0,
    Severity.CRITICAL: 1,
    Severity.MAJOR: 2,
    Severity.MINOR: 3,
}

_STATE_ORDER = {
    RiskState.ACTIVE: 0,
    RiskState.MITIGATING: 1,
    RiskState.OPEN: 2,
    RiskState.PARKED: 3,
    RiskState.CLOSED: 4,
    RiskState.ARCHIVED: 5,
}


def _escape_cell(value: str) -> str:
    """Keep one-line table cells intact regardless of the source text."""

    return value.replace("|", "\\|").replace("\n", " ").strip()


def _truncate(value: str, limit: int = 96) -> str:
    """Bound a table cell so the index stays scannable at a glance."""

    text = _escape_cell(value)
    return text if len(text) <= limit else text[: limit - 1] + "…"


def render_index(snapshot: ParkingSnapshot) -> str:
    """Render the active-risk index: one line per risk, live risks first."""

    live = sorted(
        (risk for risk in snapshot.risks if risk.live),
        key=lambda risk: (_SEVERITY_ORDER[risk.severity], _STATE_ORDER[risk.state], risk.id),
    )
    settled = sorted(
        (risk for risk in snapshot.risks if not risk.live),
        key=lambda risk: risk.id,
    )
    pending_by_subject: dict[str, int] = {}
    for row in snapshot.pending:
        pending_by_subject[row.subject] = pending_by_subject.get(row.subject, 0) + 1

    lines = [
        RISK_INDEX_MARKER,
        "# Risk Parking Index",
        "",
        "Generated view. `judgments.yaml` and `events.yaml` are authoritative;",
        "each risk's own file holds its full history. Do not edit this file.",
        "",
        f"Live: {len(live)} · Settled: {len(settled)} · Pending decisions: {len(snapshot.pending)}",
        "",
        "## Live",
        "",
    ]
    if live:
        lines.extend(
            render_rows_table(
                ("ID", "Severity", "State", "Title", "Trigger", "Pending"),
                [
                    (
                        f"[{risk.id}](risks/{risk.id}.md)",
                        risk.severity.value,
                        risk.state.value,
                        _truncate(risk.title),
                        _truncate(risk.trigger, 64),
                        str(pending_by_subject.get(risk.id, 0)) or "0",
                    )
                    for risk in live
                ],
            )
        )
    else:
        lines.append("No live risks.")
    lines.extend(["", "## Settled", ""])
    if settled:
        lines.extend(
            render_rows_table(
                ("ID", "State", "Title"),
                [
                    (f"[{risk.id}](risks/{risk.id}.md)", risk.state.value, _truncate(risk.title))
                    for risk in settled
                ],
            )
        )
    else:
        lines.append("No settled risks.")
    return "\n".join(lines) + "\n"


def render_judge_view(snapshot: ParkingSnapshot) -> str:
    """Render the pending-decision queue above the settled decision history."""

    pending = snapshot.pending
    settled = snapshot.settled
    lines = [
        JUDGE_VIEW_MARKER,
        "# Judgment Ledger",
        "",
        "Generated view of `judgments.yaml`, which is append-only and is never",
        "compacted. Speak decisions in chat; the agent records them through",
        "`devola-parking decide`. Do not edit this file.",
        "",
        f"Pending: {len(pending)} · Settled: {len(settled)}",
        "",
        "## Pending Decisions",
        "",
    ]
    if pending:
        lines.extend(
            render_rows_table(
                ("ID", "Subject", "Question", "Raised"),
                [
                    (
                        row.id,
                        _truncate(row.subject, 32),
                        _truncate(row.question, 120),
                        row.raised_at,
                    )
                    for row in pending
                ],
            )
        )
    else:
        lines.append("No pending decisions.")
    lines.extend(["", "## Settled Decisions", ""])
    if settled:
        for row in settled:
            supersedes = f" (answers {row.supersedes})" if row.supersedes else ""
            lines.extend(
                [
                    f"### {row.id} — {_escape_cell(row.subject)}{supersedes}",
                    "",
                    f"**Question**: {row.question}",
                    "",
                    f"**Decision**: {row.decision}",
                    "",
                    f"_Decided {row.decided_at}_",
                    "",
                ]
            )
    else:
        lines.extend(["No settled decisions.", ""])
    return "\n".join(lines).rstrip("\n") + "\n"


__all__ = ["render_index", "render_judge_view"]
