#!/usr/bin/env bash
# DevolaFlow host-bridge boundary hook (claude).
# Generated by `python -m devolaflow.hostbridge install claude` — do not hand-edit.
# Fail-open by contract: every error path allows.

# R5 strict fast path: enforcement off -> allow WITHOUT starting Python.
if [ "$DEVOLAFLOW_HOST_ENFORCE" != "1" ]; then
  :
  exit 0
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

if [ -x "$REPO_ROOT/.venv/bin/python" ]; then
  PY="$REPO_ROOT/.venv/bin/python"
elif command -v python3 >/dev/null 2>&1; then
  PY="python3"
else
  # No interpreter available -> allow (fail-open).
  exit 0
fi

cd "$REPO_ROOT" || { exit 0; }
exec "$PY" -m devolaflow.hostbridge --host claude
