"""clean_repo Phase B1 — regression suite for the archiver upgrade.

Covers the three new behaviours of ``scripts/archive_research_artifacts.py``
(subdirectory recursion, ``--refresh``, ``--misc``) plus the DEFAULT-path
byte-equivalence regression pin (spec:
``.local/tasks/clean_repo/02-phase-B-archive.md`` step 2 — the default
invocation must keep producing the exact pre-B1 archive tree, byte for
byte, for inputs the pre-B1 script fully handled).

Every test runs against a ``tmp_path`` sandbox — ``_find_root`` is
monkeypatched so the script never touches the real repository tree.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

_SCRIPT = Path(__file__).resolve().parents[1] / "scripts" / "archive_research_artifacts.py"


def _load_archiver():
    spec = importlib.util.spec_from_file_location("archive_research_artifacts_b1", _SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules["archive_research_artifacts_b1"] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture()
def archiver(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    """Script module wired to a tmp_path sandbox root."""
    mod = _load_archiver()
    monkeypatch.setattr(mod, "_find_root", lambda: tmp_path)
    (tmp_path / ".local" / "research").mkdir(parents=True)
    return mod


def _research(tmp_path: Path) -> Path:
    return tmp_path / ".local" / "research"


def _dest(tmp_path: Path, leaf: str) -> Path:
    return tmp_path / "docs" / "cycle-archive" / leaf


def test_subdir_recursion_preserves_structure(archiver, tmp_path: Path) -> None:
    """Subdirs and evaluator artifacts route without flattening or history loss."""
    research = _research(tmp_path)
    (research / "v9.9.0_patches" / "nested").mkdir(parents=True)
    (research / "v9.9.0_patches" / "p1.md").write_text("patch-1", encoding="utf-8")
    (research / "v9.9.0_patches" / "nested" / "p2.md").write_text("patch-2", encoding="utf-8")
    (research / "v9.9.0_gap_analysis.md").write_text("gap", encoding="utf-8")
    (research / "v9.9.0_harness_evaluation.json").write_text("{}", encoding="utf-8")
    (research / "v9.9.0_nines.json").write_text("{}", encoding="utf-8")

    assert archiver.archive("9.9.0") == 0

    dest = _dest(tmp_path, "v9.9.0")
    assert (dest / "v9.9.0_patches" / "p1.md").read_text(encoding="utf-8") == "patch-1"
    assert (dest / "v9.9.0_patches" / "nested" / "p2.md").read_text(encoding="utf-8") == "patch-2"
    assert (dest / "v9.9.0_gap_analysis.md").read_text(encoding="utf-8") == "gap"
    assert (dest / "harness" / "v9.9.0_harness_evaluation.json").is_file()
    # Legacy NineS artifacts keep their historical route for archive compatibility.
    assert (dest / "nines" / "v9.9.0_nines.json").is_file()
    # The README index lists the subdir (trailing slash), NOT its contents
    # flattened into the flat buckets.
    readme = (dest / "README.md").read_text(encoding="utf-8")
    assert "* `v9.9.0_patches/`" in readme
    assert "### harness" in readme
    assert "### nines" in readme
    assert not (dest / "other" / "p1.md").exists()


def test_default_path_byte_equivalent_regression(archiver, tmp_path: Path) -> None:
    """Default invocation reproduces the pre-B1 archive tree byte-for-byte.

    The expected README below is EXACTLY what the pre-B1 script
    generated (verified against `git show` of the pre-change script at
    B1 authoring time); the bucket→path layout is the pre-B1 mapping.
    Any drift in this test is a W-19 archive-semantics regression.
    """
    research = _research(tmp_path)
    sources = {
        "v9.9.0_gap_analysis.md": "GA",
        "v9.9.0_implementation_plan.md": "IP",
        "v9.9.0_pv01_design.md": "D",
        "v9.9.0_nines.json": "{}",
        "v9.9.0_evaluation.md": "E",
        "v9.9.0_retrospective.md": "R",
        "v9.9.0_conflict_register.md": "O",
    }
    for name, body in sources.items():
        (research / name).write_text(body, encoding="utf-8")

    assert archiver.archive("9.9.0") == 0

    dest = _dest(tmp_path, "v9.9.0")
    produced = {
        str(p.relative_to(dest)): p.read_text(encoding="utf-8")
        for p in dest.rglob("*")
        if p.is_file()
    }
    expected_readme = (
        "# Cycle Archive — v9.9.0\n"
        "\n"
        "Auto-generated by `scripts/archive_research_artifacts.py` per Workflow\n"
        "Rule W-19. Mirrors the `.local/research/v9.9*` artifacts so\n"
        "future cycle-N+1 planning gates can reference cycle-N research without\n"
        "depending on `.local/` (which is gitignored on most clones).\n"
        "\n"
        "## Contents\n"
        "\n"
        "### gap_analysis\n"
        "\n"
        "* `v9.9.0_gap_analysis.md`\n"
        "\n"
        "### implementation_plan\n"
        "\n"
        "* `v9.9.0_implementation_plan.md`\n"
        "\n"
        "### design\n"
        "\n"
        "* `v9.9.0_pv01_design.md`\n"
        "\n"
        "### nines\n"
        "\n"
        "* `v9.9.0_nines.json`\n"
        "\n"
        "### evaluation\n"
        "\n"
        "* `v9.9.0_evaluation.md`\n"
        "\n"
        "### retrospective\n"
        "\n"
        "* `v9.9.0_retrospective.md`\n"
        "\n"
        "### other\n"
        "\n"
        "* `v9.9.0_conflict_register.md`\n"
        "\n"
        "## Cross-references\n"
        "\n"
        "* `CHANGELOG.md` `## [9.9.0]` — release note\n"
        "* `.local/research/` — live research workspace (gitignored)\n"
        "* `AGENTS.md` §W-19 — archive policy\n"
    )
    assert produced == {
        "README.md": expected_readme,
        "v9.9.0_gap_analysis.md": "GA",
        "v9.9.0_implementation_plan.md": "IP",
        "design/v9.9.0_pv01_design.md": "D",
        "nines/v9.9.0_nines.json": "{}",
        "evaluation/v9.9.0_evaluation.md": "E",
        "v9.9.0_retrospective.md": "R",
        "other/v9.9.0_conflict_register.md": "O",
    }


def test_stale_copy_without_refresh_left_untouched(archiver, tmp_path: Path, capsys) -> None:
    """A drifted destination copy is reported STALE, never overwritten by default."""
    research = _research(tmp_path)
    (research / "v9.9.0_retrospective.md").write_text("NEW", encoding="utf-8")
    dest = _dest(tmp_path, "v9.9.0")
    dest.mkdir(parents=True)
    (dest / "v9.9.0_retrospective.md").write_text("OLD", encoding="utf-8")

    assert archiver.archive("9.9.0") == 0

    assert (dest / "v9.9.0_retrospective.md").read_text(encoding="utf-8") == "OLD"
    out = capsys.readouterr().out
    assert "STALE" in out
    assert "--refresh" in out
    assert "REFRESH " not in out


def test_refresh_overwrites_stale_copy(archiver, tmp_path: Path, capsys) -> None:
    """--refresh overwrites a drifted destination copy (status REFRESH)."""
    research = _research(tmp_path)
    (research / "v9.9.0_retrospective.md").write_text("NEW", encoding="utf-8")
    dest = _dest(tmp_path, "v9.9.0")
    dest.mkdir(parents=True)
    (dest / "v9.9.0_retrospective.md").write_text("OLD", encoding="utf-8")

    assert archiver.archive("9.9.0", refresh=True) == 0

    assert (dest / "v9.9.0_retrospective.md").read_text(encoding="utf-8") == "NEW"
    assert "REFRESH" in capsys.readouterr().out

    # Idempotence: a second refresh run is a byte-level no-op (EXISTS).
    assert archiver.archive("9.9.0", refresh=True) == 0
    out = capsys.readouterr().out
    assert "REFRESH " not in out
    assert "EXISTS" in out


def test_refresh_regenerates_readme_index(archiver, tmp_path: Path) -> None:
    """The README index is regenerated under --refresh when sources changed."""
    research = _research(tmp_path)
    (research / "v9.9.0_retrospective.md").write_text("R", encoding="utf-8")
    assert archiver.archive("9.9.0") == 0
    readme_path = _dest(tmp_path, "v9.9.0") / "README.md"
    assert "gap_analysis" not in readme_path.read_text(encoding="utf-8")

    (research / "v9.9.0_gap_analysis.md").write_text("GA", encoding="utf-8")

    # Default path: README untouched (legacy exists-means-skip semantics).
    assert archiver.archive("9.9.0") == 0
    assert "v9.9.0_gap_analysis.md" not in readme_path.read_text(encoding="utf-8")

    # Refresh path: index regenerated to match the changed source set.
    assert archiver.archive("9.9.0", refresh=True) == 0
    assert "* `v9.9.0_gap_analysis.md`" in readme_path.read_text(encoding="utf-8")


def test_misc_archives_only_nonversioned_root_files(archiver, tmp_path: Path) -> None:
    """--misc gathers cycle-less root files; dirs + cycle-versioned files excluded.

    Cycle-LESS ``v``-prefixed names (``v10_internal_...`` — no
    ``v<MAJOR>.<MINOR>.`` component) route to misc/ because no cycle
    prefix can ever gather them; dot-form (``v9.9.0_...``) and dash-form
    (``v15-cycle_...``) versioned names stay out of misc.
    """
    research = _research(tmp_path)
    (research / "survey.md").write_text("S", encoding="utf-8")
    (research / "notes_analysis.md").write_text("N", encoding="utf-8")
    (research / "v10_internal_directions.md").write_text("I", encoding="utf-8")
    (research / "v9.9.0_gap_analysis.md").write_text("V", encoding="utf-8")
    (research / "v15-cycle_design_review.md").write_text("C", encoding="utf-8")
    (research / "adr").mkdir()
    (research / "adr" / "some-adr.md").write_text("A", encoding="utf-8")

    assert archiver.archive_misc() == 0

    dest = _dest(tmp_path, "misc")
    produced = sorted(str(p.relative_to(dest)) for p in dest.rglob("*") if p.is_file())
    assert produced == ["README.md", "notes_analysis.md", "survey.md", "v10_internal_directions.md"]
    readme = (dest / "README.md").read_text(encoding="utf-8")
    assert "* `notes_analysis.md`" in readme
    assert "* `survey.md`" in readme
    assert "* `v10_internal_directions.md`" in readme
    assert "v9.9.0_gap_analysis.md" not in readme
    assert "v15-cycle_design_review.md" not in readme


def test_misc_supports_dry_run_and_refresh(archiver, tmp_path: Path, capsys) -> None:
    """--misc honours --dry-run (zero writes) and --refresh (stale heal)."""
    research = _research(tmp_path)
    (research / "survey.md").write_text("NEW", encoding="utf-8")
    dest = _dest(tmp_path, "misc")

    assert archiver.archive_misc(dry_run=True) == 0
    assert not dest.exists()
    assert "WOULD" in capsys.readouterr().out

    dest.mkdir(parents=True)
    (dest / "survey.md").write_text("OLD", encoding="utf-8")
    assert archiver.archive_misc() == 0
    assert (dest / "survey.md").read_text(encoding="utf-8") == "OLD"
    assert "STALE" in capsys.readouterr().out

    assert archiver.archive_misc(refresh=True) == 0
    assert (dest / "survey.md").read_text(encoding="utf-8") == "NEW"
    assert "REFRESH" in capsys.readouterr().out


def test_cli_version_and_misc_mutually_exclusive(
    archiver, monkeypatch: pytest.MonkeyPatch, capsys
) -> None:
    """CLI: exactly one of <version> / --misc — both or neither error out."""
    for argv in (
        ["archive_research_artifacts.py", "9.9.0", "--misc"],
        ["archive_research_artifacts.py"],
    ):
        monkeypatch.setattr(sys, "argv", argv)
        with pytest.raises(SystemExit) as excinfo:
            archiver.main()
        assert excinfo.value.code not in (0, None)
        capsys.readouterr()  # swallow argparse usage output
