"""Parity and consumer checks for the generated browser seed catalog."""

from __future__ import annotations

import importlib.util
import json
import re
import sys
from pathlib import Path

import yaml


def _load_generator(project_root: Path):
    path = project_root / "scripts" / "generate_demo_seed_catalog.py"
    spec = importlib.util.spec_from_file_location("generate_demo_seed_catalog", path)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _load_generated_catalog(project_root: Path) -> tuple[bytes, dict]:
    path = project_root / "workflow-system/human/demo/shared/seed-catalog.js"
    source = path.read_bytes()
    match = re.fullmatch(
        rb"// AUTO-GENERATED by scripts/generate_demo_seed_catalog\.py\. DO NOT EDIT\.\n"
        rb"window\.DEVOLAFLOW_SEED_CATALOG = Object\.freeze\(\n"
        rb"(.*)\n\);\n",
        source,
        re.DOTALL,
    )
    assert match, "generated catalog wrapper or do-not-edit comment drifted"
    return source, json.loads(match.group(1))


def test_generated_catalog_preserves_registry_and_seed_provenance(project_root: Path):
    """All 26 records must preserve registry order and seed YAML decomposition bytes."""
    _, catalog = _load_generated_catalog(project_root)
    templates_root = project_root / "workflow-system/agent/templates"
    registry = yaml.safe_load((templates_root / "registry.yaml").read_text(encoding="utf-8"))
    entries = [*(registry["compositions"]), *(registry["templates"])]

    assert catalog["schema_version"] == "1.0"
    assert catalog["registry"] == {
        "schema_version": "3.0",
        "source_path": "workflow-system/agent/templates/registry.yaml",
    }
    assert catalog["record_count"] == len(catalog["seeds"]) == len(entries) == 26
    assert [record["name"] for record in catalog["seeds"]] == [entry["name"] for entry in entries]

    for entry, record in zip(entries, catalog["seeds"], strict=True):
        seed = yaml.safe_load((templates_root / entry["seed"]).read_text(encoding="utf-8"))
        assert record["registry_schema_version"] == registry["schema_version"]
        assert record["seed_schema_version"] == seed["schema_version"]
        assert record["source"] == seed["metadata"]["source"]
        assert record["category"] == entry["category"]
        assert record["tags"] == entry["tags"]
        assert record["description"] == entry["description"]
        assert record["seed_path"] == f"workflow-system/agent/templates/{entry['seed']}"
        if "path" in entry:
            assert record["runtime_path"] == (f"workflow-system/agent/templates/{entry['path']}")
        else:
            assert "runtime_path" not in record

        expected_partitions = []
        for partition in seed["partitions"]:
            expected_partitions.append(
                {
                    "key": partition["key"],
                    "title": partition["title_template"],
                    "source_stages": partition["source_stages"],
                    "assertions": [
                        {
                            "key": assertion["key"],
                            "statement": assertion["statement_template"],
                            "suggested_priority": assertion["suggested_priority"],
                            "verify": assertion["verify"],
                        }
                        for assertion in partition["assertions"]
                    ],
                }
            )
        assert record["partitions"] == expected_partitions


def test_generator_is_byte_idempotent_and_check_mode_detects_stale(
    project_root: Path, monkeypatch, tmp_path: Path
):
    """Rendering is deterministic and --check rejects stale or CRLF output."""
    source, _ = _load_generated_catalog(project_root)
    generator = _load_generator(project_root)

    assert generator.render_catalog_bytes() == source
    assert generator.render_catalog_bytes() == source
    assert source.endswith(b"\n")
    assert b"\r" not in source

    check_target = tmp_path / "seed-catalog.js"
    monkeypatch.setattr(generator, "OUTPUT_PATH", check_target)
    monkeypatch.setattr(sys, "argv", ["generate_demo_seed_catalog.py", "--check"])
    check_target.write_bytes(b"// stale\r\n")
    assert generator.main() == 1
    check_target.write_bytes(source.replace(b"\n", b"\r\n"))
    assert generator.main() == 1
    check_target.write_bytes(source)
    assert generator.main() == 0

    monkeypatch.setattr(sys, "argv", ["generate_demo_seed_catalog.py"])
    check_target.write_bytes(b"// stale again\r\n")
    assert generator.main() == 0
    assert check_target.read_bytes() == source


def test_consumers_share_catalog_and_load_it_before_consumer_code(project_root: Path):
    """Home, Seed Library, and Explorer must not own a second seed universe."""
    demo_root = project_root / "workflow-system/human/demo"
    home = (demo_root / "index.html").read_text(encoding="utf-8")
    library_html = (demo_root / "workflow-visualizer/index.html").read_text(encoding="utf-8")
    library_js = (demo_root / "workflow-visualizer/visualizer.js").read_text(encoding="utf-8")
    explorer_html = (demo_root / "stage-explorer/index.html").read_text(encoding="utf-8")
    explorer_js = (demo_root / "stage-explorer/explorer.js").read_text(encoding="utf-8")

    assert home.index('src="shared/seed-catalog.js"') < home.index("function renderHomeSeedCatalog")
    assert library_html.index('src="../shared/seed-catalog.js"') < library_html.index(
        'src="visualizer.js"'
    )
    assert explorer_html.index('src="../shared/seed-catalog.js"') < explorer_html.index(
        'src="explorer.js"'
    )
    assert "window.DEVOLAFLOW_SEED_CATALOG" in home
    assert "window.DEVOLAFLOW_SEED_CATALOG" in library_js
    assert "window.DEVOLAFLOW_SEED_CATALOG" in explorer_js
    assert "const SEEDS = [" not in library_js
    assert not re.search(r"\bseeds\s*:\s*\[", explorer_js)
    assert "primitive.seeds" not in explorer_js
    assert not re.search(r"<li><code>[a-z0-9-]+</code></li>", home)
    assert "<noscript>" in home
    assert 'href="workflow-visualizer/index.html"' in home

    for source in (home, library_js, explorer_js):
        assert "console.warn" in source
        assert "unavailable or malformed" in source
