"""Host-config installer — ``python -m devolaflow.hostbridge install <host>``.

v17.0.0 R2 (design §D-R2-3 dogfood): (re)generates the per-host bridge
configuration idempotently. ``cursor`` / ``claude`` / ``codex`` write
project-level files (the same artifacts committed to this repo);
``kimi`` has NO project-level config surface (Beta, user-level
``~/.kimi-code/config.toml``) so the installer PRINTS the ``[[hooks]]``
TOML snippet for the operator to paste.

All generated configs are FAIL-OPEN by construction: the bash wrappers
fast-path to allow in pure bash when ``DEVOLAFLOW_HOST_ENFORCE`` is not
``"1"`` (no Python startup), and no host config sets a fail-closed
option. The Claude Code merge is ADDITIVE — existing ``settings.json``
keys and foreign hook entries are preserved; only entries invoking
``devola-boundary.sh`` are (re)written.
"""

from __future__ import annotations

import argparse
import json
import stat
import sys
from pathlib import Path

INSTALL_HOSTS: tuple[str, ...] = ("cursor", "claude", "codex", "kimi", "copilot")

_SCRIPT_NAME = "devola-boundary.sh"
_MARKER = "devola-boundary.sh"
# v17 R4 session-start resume hook — Cursor + Claude only (see
# references/host-bridges.md §8 for the Codex/Kimi/DSH downgrade note).
_SESSION_SCRIPT_NAME = "devola-session.sh"
_SESSION_MARKER = "devola-session.sh"


def _render_boundary_script(host: str) -> str:
    """Bash wrapper with a pure-bash fast path (no Python when flag off).

    * cursor — allow is a stdout JSON permission; always exit 0.
    * claude / codex — allow is a silent exit 0; deny propagates the
      bridge's exit 2 + stderr through ``exec``.
    """
    if host == "cursor":
        allow = 'echo \'{"permission":"allow"}\''
        fallback = f"{allow}\n  exit 0"
    else:
        allow = ":"
        fallback = "exit 0"
    return f"""#!/usr/bin/env bash
# DevolaFlow host-bridge boundary hook ({host}).
# Generated by `python -m devolaflow.hostbridge install {host}` — do not hand-edit.
# Fail-open by contract: every error path allows.

# R5 strict fast path: enforcement off -> allow WITHOUT starting Python.
if [ "$DEVOLAFLOW_HOST_ENFORCE" != "1" ]; then
  {allow}
  exit 0
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

if [ -x "$REPO_ROOT/.venv/bin/python" ]; then
  PY="$REPO_ROOT/.venv/bin/python"
elif command -v python3 >/dev/null 2>&1; then
  PY="python3"
else
  # No interpreter available -> allow (fail-open).
  {fallback}
fi

cd "$REPO_ROOT" || {{ {fallback}; }}
exec "$PY" -m devolaflow.hostbridge --host {host}
"""


def _render_session_script(host: str) -> str:
    """Bash session-start wrapper with a pure-bash fast path.

    Gated on ``DEVOLAFLOW_AGENT_WORKSPACE`` (W-20 REUSE — the workspace-
    engagement surface, NOT the boundary-enforcement flag). Flag off →
    silent exit 0 without starting Python; empty stdout means the host
    injects no context. Every error path degrades to silent exit 0.
    """
    return f"""#!/usr/bin/env bash
# DevolaFlow session-start resume hook ({host}).
# Generated by `python -m devolaflow.hostbridge install {host}` — do not hand-edit.
# Read-only: prints a resume summary for context injection; every error
# path degrades to empty output + exit 0.

# R5 strict fast path: workspace engagement off -> silent, no Python.
if [ "$DEVOLAFLOW_AGENT_WORKSPACE" != "1" ]; then
  exit 0
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

if [ -x "$REPO_ROOT/.venv/bin/python" ]; then
  PY="$REPO_ROOT/.venv/bin/python"
elif command -v python3 >/dev/null 2>&1; then
  PY="python3"
else
  # No interpreter available -> no context injected.
  exit 0
fi

cd "$REPO_ROOT" || exit 0
exec "$PY" -m devolaflow.hostbridge resume --host {host}
"""


def _render_cursor_hooks_json() -> str:
    config = {
        "version": 1,
        "hooks": {
            "preToolUse": [
                {
                    "matcher": "Write|StrReplace",
                    "command": ".cursor/hooks/devola-boundary.sh",
                }
            ],
            "beforeShellExecution": [{"command": ".cursor/hooks/devola-boundary.sh"}],
            "sessionStart": [{"command": ".cursor/hooks/devola-session.sh"}],
        },
    }
    return json.dumps(config, indent=2) + "\n"


def _render_copilot_hooks_json() -> str:
    config = {
        "version": 1,
        "hooks": {
            "preToolUse": [
                {
                    "type": "command",
                    "command": ".github/hooks/devola-boundary.sh",
                    "timeoutSec": 30,
                }
            ]
        },
    }
    return json.dumps(config, indent=2) + "\n"


def _render_codex_hooks_json() -> str:
    config = {
        "version": 1,
        "hooks": {
            "PreToolUse": [
                {
                    "matcher": "^(Bash|apply_patch)$",
                    "command": ".codex/hooks/devola-boundary.sh",
                }
            ]
        },
    }
    return json.dumps(config, indent=2) + "\n"


def _claude_hook_entries() -> list[dict]:
    command = '"$CLAUDE_PROJECT_DIR"/.claude/hooks/devola-boundary.sh'
    return [
        {
            "matcher": "Edit|Write|MultiEdit",
            "hooks": [{"type": "command", "command": command}],
        },
        {
            "matcher": "Bash",
            "hooks": [{"type": "command", "command": command}],
        },
    ]


def _claude_session_hook_entries() -> list[dict]:
    command = '"$CLAUDE_PROJECT_DIR"/.claude/hooks/devola-session.sh'
    return [
        {
            "matcher": "startup|resume",
            "hooks": [{"type": "command", "command": command}],
        }
    ]


def _merge_claude_settings(existing_text: str | None) -> str:
    """Merge the hooks block additively into ``.claude/settings.json``.

    Existing top-level keys and foreign ``PreToolUse`` / ``SessionStart``
    entries are preserved verbatim; entries whose command invokes
    ``devola-boundary.sh`` / ``devola-session.sh`` are replaced
    (idempotent re-runs).
    """
    settings: dict = {}
    if existing_text:
        settings = json.loads(existing_text)
        if not isinstance(settings, dict):
            raise ValueError(".claude/settings.json is not a JSON object — refusing to merge")

    hooks = settings.setdefault("hooks", {})

    def _replace_ours(event: str, marker: str, ours: list[dict]) -> None:
        def _is_ours(entry: dict) -> bool:
            return any(marker in str(hook.get("command", "")) for hook in entry.get("hooks", []))

        kept = [entry for entry in hooks.get(event, []) if not _is_ours(entry)]
        hooks[event] = kept + ours

    _replace_ours("PreToolUse", _MARKER, _claude_hook_entries())
    _replace_ours("SessionStart", _SESSION_MARKER, _claude_session_hook_entries())
    return json.dumps(settings, indent=2) + "\n"


def _write_if_changed(path: Path, content: str, *, executable: bool = False) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        status = "unchanged"
    else:
        path.write_text(content, encoding="utf-8")
        status = "written"
    if executable:
        mode = path.stat().st_mode
        path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return status


def install_cursor(repo_root: Path) -> dict[str, str]:
    return {
        ".cursor/hooks.json": _write_if_changed(
            repo_root / ".cursor" / "hooks.json", _render_cursor_hooks_json()
        ),
        ".cursor/hooks/devola-boundary.sh": _write_if_changed(
            repo_root / ".cursor" / "hooks" / _SCRIPT_NAME,
            _render_boundary_script("cursor"),
            executable=True,
        ),
        ".cursor/hooks/devola-session.sh": _write_if_changed(
            repo_root / ".cursor" / "hooks" / _SESSION_SCRIPT_NAME,
            _render_session_script("cursor"),
            executable=True,
        ),
    }


def install_claude(repo_root: Path) -> dict[str, str]:
    settings_path = repo_root / ".claude" / "settings.json"
    existing = settings_path.read_text(encoding="utf-8") if settings_path.is_file() else None
    return {
        ".claude/settings.json": _write_if_changed(settings_path, _merge_claude_settings(existing)),
        ".claude/hooks/devola-boundary.sh": _write_if_changed(
            repo_root / ".claude" / "hooks" / _SCRIPT_NAME,
            _render_boundary_script("claude"),
            executable=True,
        ),
        ".claude/hooks/devola-session.sh": _write_if_changed(
            repo_root / ".claude" / "hooks" / _SESSION_SCRIPT_NAME,
            _render_session_script("claude"),
            executable=True,
        ),
    }


def install_codex(repo_root: Path) -> dict[str, str]:
    return {
        ".codex/hooks.json": _write_if_changed(
            repo_root / ".codex" / "hooks.json", _render_codex_hooks_json()
        ),
        ".codex/hooks/devola-boundary.sh": _write_if_changed(
            repo_root / ".codex" / "hooks" / _SCRIPT_NAME,
            _render_boundary_script("codex"),
            executable=True,
        ),
    }


def _render_copilot_boundary_script() -> str:
    """Render a Copilot wrapper that always exits zero."""
    return """#!/usr/bin/env bash
# DevolaFlow host-bridge boundary hook (copilot).
# Generated by `python -m devolaflow.hostbridge install copilot` — do not hand-edit.
# Copilot command hooks are fail-closed; this wrapper normalizes all internal
# failures to an explicit allow response and exit 0.

if [ "$DEVOLAFLOW_HOST_ENFORCE" != "1" ]; then
  printf '%s\\n' '{"permissionDecision":"allow"}'
  exit 0
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

if [ -x "$REPO_ROOT/.venv/bin/python" ]; then
  PY="$REPO_ROOT/.venv/bin/python"
elif command -v python3 >/dev/null 2>&1; then
  PY="python3"
else
  printf '%s\\n' '{"permissionDecision":"allow"}'
  exit 0
fi

cd "$REPO_ROOT" || {
  printf '%s\\n' '{"permissionDecision":"allow"}'
  exit 0
}

response="$("$PY" -m devolaflow.hostbridge --host copilot 2>/dev/null)"
status=$?
if [ "$status" -ne 0 ] || [ -z "$response" ]; then
  printf '%s\\n' '{"permissionDecision":"allow"}'
else
  printf '%s\\n' "$response"
fi
exit 0
"""


def install_copilot(repo_root: Path) -> dict[str, str]:
    return {
        ".github/hooks/devola-boundary.json": _write_if_changed(
            repo_root / ".github" / "hooks" / "devola-boundary.json",
            _render_copilot_hooks_json(),
        ),
        ".github/hooks/devola-boundary.sh": _write_if_changed(
            repo_root / ".github" / "hooks" / "devola-boundary.sh",
            _render_copilot_boundary_script(),
            executable=True,
        ),
    }


def kimi_snippet() -> str:
    """The user-level ``[[hooks]]`` TOML block for ``~/.kimi-code/config.toml``."""
    return """# DevolaFlow host-bridge boundary hook (KimiCode, Beta user-level config).
# Paste into ~/.kimi-code/config.toml. Requires `devolaflow` importable by
# the `python3` on PATH (e.g. `pip install devolaflow` or a repo venv on
# PATH). Fail-open: KimiCode treats hook timeouts as allow.
[[hooks]]
event = "PreToolUse"
matcher = "WriteFile|StrReplaceFile|Shell"
command = "python3 -m devolaflow.hostbridge --host kimi"
timeout_ms = 5000
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m devolaflow.hostbridge install",
        description="(Re)generate per-host DevolaFlow boundary-bridge configs.",
    )
    parser.add_argument("host", choices=INSTALL_HOSTS)
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=None,
        help="project root to install into (default: current directory)",
    )
    args = parser.parse_args(argv)
    repo_root = (args.repo_root or Path.cwd()).resolve()

    if args.host == "kimi":
        sys.stdout.write(kimi_snippet())
        return 0

    installers = {
        "cursor": install_cursor,
        "claude": install_claude,
        "codex": install_codex,
        "copilot": install_copilot,
    }
    results = installers[args.host](repo_root)
    for rel_path, status in results.items():
        print(f"[hostbridge-install] {rel_path:<40s} {status}")
    return 0


__all__ = [
    "INSTALL_HOSTS",
    "install_claude",
    "install_codex",
    "install_copilot",
    "install_cursor",
    "kimi_snippet",
    "main",
]
