// AUTO-GENERATED by scripts/generate_demo_seed_catalog.py. DO NOT EDIT.
window.DEVOLAFLOW_SEED_CATALOG = Object.freeze(
{
  "schema_version": "1.0",
  "registry": {
    "schema_version": "3.0",
    "source_path": "workflow-system/agent/templates/registry.yaml"
  },
  "record_count": 23,
  "seeds": [
    {
      "registry_schema_version": "3.0",
      "seed_schema_version": "1.0",
      "source": {
        "kind": "composition",
        "name": "hotfix",
        "path": "workflow-system/agent/templates/registry.yaml",
        "schema_version": "2.0"
      },
      "name": "hotfix",
      "category": "build",
      "tags": [
        "bug",
        "fix",
        "hotfix",
        "patch",
        "urgent"
      ],
      "description": "Rapid bug triage, minimal fix, focused test, fast-track release.",
      "seed_path": "workflow-system/agent/templates/seeds/hotfix.yaml",
      "partitions": [
        {
          "key": "diagnosis",
          "title": "Bug diagnosis",
          "source_stages": [
            {
              "id": "bug_triage",
              "primitive": "analyze"
            }
          ],
          "assertions": [
            {
              "key": "cause-reproduced",
              "statement": "The defect is reproducible and its root cause is isolated",
              "suggested_priority": "P0",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        },
        {
          "key": "remediation",
          "title": "Minimal remediation",
          "source_stages": [
            {
              "id": "fix",
              "primitive": "implement"
            },
            {
              "id": "test",
              "primitive": "test"
            }
          ],
          "assertions": [
            {
              "key": "regression-covered",
              "statement": "The minimal fix passes focused regression coverage with no unrelated changes",
              "suggested_priority": "P0",
              "verify": {
                "mode": "metric",
                "template": "focused_test_failures == 0"
              }
            }
          ]
        },
        {
          "key": "release",
          "title": "Fast-track release",
          "source_stages": [
            {
              "id": "release",
              "primitive": "release"
            }
          ],
          "assertions": [
            {
              "key": "release-safe",
              "statement": "Release evidence and rollback instructions are ready before fast-track publication",
              "suggested_priority": "P0",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        }
      ]
    },
    {
      "registry_schema_version": "3.0",
      "seed_schema_version": "1.0",
      "source": {
        "kind": "composition",
        "name": "research-only",
        "path": "workflow-system/agent/templates/registry.yaml",
        "schema_version": "2.0"
      },
      "name": "research-only",
      "category": "discover",
      "tags": [
        "research",
        "compare",
        "evaluate"
      ],
      "description": "Pure research and comparison with a validated report.",
      "seed_path": "workflow-system/agent/templates/seeds/research-only.yaml",
      "partitions": [
        {
          "key": "investigation",
          "title": "Research and comparison",
          "source_stages": [
            {
              "id": "research",
              "primitive": "research"
            },
            {
              "id": "compare",
              "primitive": "analyze"
            }
          ],
          "assertions": [
            {
              "key": "alternatives-evidenced",
              "statement": "Relevant alternatives are compared against explicit criteria with cited evidence",
              "suggested_priority": "P1",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        },
        {
          "key": "report",
          "title": "Validated report",
          "source_stages": [
            {
              "id": "report",
              "primitive": "validate"
            }
          ],
          "assertions": [
            {
              "key": "recommendation-traceable",
              "statement": "Every recommendation is traceable to findings, constraints, and unresolved uncertainty",
              "suggested_priority": "P1",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        }
      ]
    },
    {
      "registry_schema_version": "3.0",
      "seed_schema_version": "1.0",
      "source": {
        "kind": "composition",
        "name": "design-only",
        "path": "workflow-system/agent/templates/registry.yaml",
        "schema_version": "2.0"
      },
      "name": "design-only",
      "category": "shape",
      "tags": [
        "design",
        "research",
        "review",
        "architecture"
      ],
      "description": "Research-backed design and architecture review.",
      "seed_path": "workflow-system/agent/templates/seeds/design-only.yaml",
      "partitions": [
        {
          "key": "context",
          "title": "Design context",
          "source_stages": [
            {
              "id": "research",
              "primitive": "research"
            }
          ],
          "assertions": [
            {
              "key": "constraints-known",
              "statement": "Design constraints, existing interfaces, and prior decisions are evidenced",
              "suggested_priority": "P1",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        },
        {
          "key": "architecture",
          "title": "Architecture and review",
          "source_stages": [
            {
              "id": "design",
              "primitive": "design"
            },
            {
              "id": "review",
              "primitive": "review"
            }
          ],
          "assertions": [
            {
              "key": "design-reviewed",
              "statement": "Architecture, interfaces, trade-offs, and failure modes pass independent review",
              "suggested_priority": "P0",
              "verify": {
                "mode": "metric",
                "template": "unresolved_design_blockers == 0"
              }
            }
          ]
        }
      ]
    },
    {
      "registry_schema_version": "3.0",
      "seed_schema_version": "1.0",
      "source": {
        "kind": "composition",
        "name": "documentation-only",
        "path": "workflow-system/agent/templates/registry.yaml",
        "schema_version": "2.0"
      },
      "name": "documentation-only",
      "category": "deliver",
      "tags": [
        "documentation",
        "docs",
        "write",
        "review"
      ],
      "description": "Documentation survey, authoring, and review.",
      "seed_path": "workflow-system/agent/templates/seeds/documentation-only.yaml",
      "partitions": [
        {
          "key": "source-survey",
          "title": "Documentation source survey",
          "source_stages": [
            {
              "id": "survey",
              "primitive": "research"
            }
          ],
          "assertions": [
            {
              "key": "truth-sources-known",
              "statement": "Behavioral claims are mapped to current source-of-truth code or specifications",
              "suggested_priority": "P1",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        },
        {
          "key": "author-review",
          "title": "Authoring and review",
          "source_stages": [
            {
              "id": "author",
              "primitive": "implement"
            },
            {
              "id": "review",
              "primitive": "review"
            }
          ],
          "assertions": [
            {
              "key": "docs-accurate",
              "statement": "Documentation is complete, link-valid, audience-appropriate, and free of ghost features",
              "suggested_priority": "P0",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        }
      ]
    },
    {
      "registry_schema_version": "3.0",
      "seed_schema_version": "1.0",
      "source": {
        "kind": "composition",
        "name": "spike-poc",
        "path": "workflow-system/agent/templates/registry.yaml",
        "schema_version": "2.0"
      },
      "name": "spike-poc",
      "category": "discover",
      "tags": [
        "spike",
        "poc",
        "prototype",
        "experiment"
      ],
      "description": "Bounded throwaway prototype with an explicit evaluation verdict.",
      "seed_path": "workflow-system/agent/templates/seeds/spike-poc.yaml",
      "partitions": [
        {
          "key": "hypothesis",
          "title": "Research hypothesis",
          "source_stages": [
            {
              "id": "research",
              "primitive": "research"
            }
          ],
          "assertions": [
            {
              "key": "question-bounded",
              "statement": "The prototype question, time box, and success threshold are explicit",
              "suggested_priority": "P1",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        },
        {
          "key": "prototype-verdict",
          "title": "Prototype and evaluation",
          "source_stages": [
            {
              "id": "prototype",
              "primitive": "implement"
            },
            {
              "id": "evaluate",
              "primitive": "validate"
            }
          ],
          "assertions": [
            {
              "key": "disposition-decided",
              "statement": "Prototype evidence supports an explicit adopt, revise, or discard verdict",
              "suggested_priority": "P0",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        }
      ]
    },
    {
      "registry_schema_version": "3.0",
      "seed_schema_version": "1.0",
      "source": {
        "kind": "composition",
        "name": "refactoring",
        "path": "workflow-system/agent/templates/registry.yaml",
        "schema_version": "2.0"
      },
      "name": "refactoring",
      "category": "build",
      "tags": [
        "refactor",
        "tech-debt",
        "improve",
        "restructure"
      ],
      "description": "Evidence-backed technical-debt restructuring.",
      "seed_path": "workflow-system/agent/templates/seeds/refactoring.yaml",
      "partitions": [
        {
          "key": "scope-plan",
          "title": "Refactoring scope and plan",
          "source_stages": [
            {
              "id": "scope_analysis",
              "primitive": "analyze"
            },
            {
              "id": "plan",
              "primitive": "plan"
            }
          ],
          "assertions": [
            {
              "key": "boundaries-fixed",
              "statement": "Behavioral invariants, ownership boundaries, and rollback points are documented before edits",
              "suggested_priority": "P0",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        },
        {
          "key": "implementation-quality",
          "title": "Implementation quality",
          "source_stages": [
            {
              "id": "implement",
              "primitive": "implement"
            },
            {
              "id": "test",
              "primitive": "test"
            },
            {
              "id": "review",
              "primitive": "review"
            }
          ],
          "assertions": [
            {
              "key": "behavior-preserved",
              "statement": "Tests and review confirm preserved behavior with reduced structural debt",
              "suggested_priority": "P0",
              "verify": {
                "mode": "metric",
                "template": "test_failures == 0 and review_blockers == 0"
              }
            }
          ]
        }
      ]
    },
    {
      "registry_schema_version": "3.0",
      "seed_schema_version": "1.0",
      "source": {
        "kind": "composition",
        "name": "feature-enhancement",
        "path": "workflow-system/agent/templates/registry.yaml",
        "schema_version": "2.0"
      },
      "name": "feature-enhancement",
      "category": "composite",
      "tags": [
        "feature",
        "enhance",
        "extend",
        "modify"
      ],
      "description": "Extend an existing feature through design, implementation, and release evidence.",
      "seed_path": "workflow-system/agent/templates/seeds/feature-enhancement.yaml",
      "partitions": [
        {
          "key": "feature-contract",
          "title": "Feature scope, design, and plan",
          "source_stages": [
            {
              "id": "scope",
              "primitive": "analyze"
            },
            {
              "id": "design",
              "primitive": "design"
            },
            {
              "id": "plan",
              "primitive": "plan"
            }
          ],
          "assertions": [
            {
              "key": "contract-reviewed",
              "statement": "Scope, interfaces, compatibility constraints, and acceptance assertions are reviewed",
              "suggested_priority": "P0",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        },
        {
          "key": "delivery",
          "title": "Feature delivery",
          "source_stages": [
            {
              "id": "implement",
              "primitive": "implement"
            },
            {
              "id": "review",
              "primitive": "review"
            },
            {
              "id": "test",
              "primitive": "test"
            },
            {
              "id": "release",
              "primitive": "release"
            }
          ],
          "assertions": [
            {
              "key": "feature-ready",
              "statement": "Implementation passes review and tests before release evidence is approved",
              "suggested_priority": "P0",
              "verify": {
                "mode": "metric",
                "template": "review_blockers == 0 and test_failures == 0"
              }
            }
          ]
        }
      ]
    },
    {
      "registry_schema_version": "3.0",
      "seed_schema_version": "1.0",
      "source": {
        "kind": "composition",
        "name": "full-pipeline",
        "path": "workflow-system/agent/templates/registry.yaml",
        "schema_version": "2.0"
      },
      "name": "full-pipeline",
      "category": "composite",
      "tags": [
        "full",
        "pipeline",
        "feature",
        "implementation",
        "release"
      ],
      "description": "Greenfield or end-to-end build decomposition knowledge.",
      "seed_path": "workflow-system/agent/templates/seeds/full-pipeline.yaml",
      "partitions": [
        {
          "key": "solution-shape",
          "title": "Solution design and plan",
          "source_stages": [
            {
              "id": "design",
              "primitive": "design"
            },
            {
              "id": "plan",
              "primitive": "plan"
            }
          ],
          "assertions": [
            {
              "key": "solution-approved",
              "statement": "Architecture, interfaces, task ownership, and acceptance assertions are approved",
              "suggested_priority": "P0",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        },
        {
          "key": "build-convergence",
          "title": "Build and convergence",
          "source_stages": [
            {
              "id": "impl",
              "primitive": "implement"
            },
            {
              "id": "review",
              "primitive": "review"
            },
            {
              "id": "test",
              "primitive": "test"
            },
            {
              "id": "verify",
              "primitive": "verify"
            },
            {
              "id": "refine",
              "primitive": "refine"
            },
            {
              "id": "testgate",
              "primitive": "validate"
            }
          ],
          "assertions": [
            {
              "key": "quality-green",
              "statement": "Implementation, review, tests, verification, and refinement converge with zero blockers",
              "suggested_priority": "P0",
              "verify": {
                "mode": "metric",
                "template": "quality_blockers == 0 and acceptance_pass_rate == 1.0"
              }
            }
          ]
        },
        {
          "key": "release",
          "title": "Release readiness",
          "source_stages": [
            {
              "id": "release",
              "primitive": "release"
            }
          ],
          "assertions": [
            {
              "key": "release-approved",
              "statement": "Release artifacts and rollback instructions receive explicit approval",
              "suggested_priority": "P1",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        }
      ]
    },
    {
      "registry_schema_version": "3.0",
      "seed_schema_version": "1.0",
      "source": {
        "kind": "composition",
        "name": "performance-optimization",
        "path": "workflow-system/agent/templates/registry.yaml",
        "schema_version": "2.0"
      },
      "name": "performance-optimization",
      "category": "build",
      "tags": [
        "performance",
        "optimize",
        "profiling",
        "benchmark",
        "speed",
        "latency"
      ],
      "description": "Profile, optimize, benchmark, and validate measurable performance.",
      "seed_path": "workflow-system/agent/templates/seeds/performance-optimization.yaml",
      "partitions": [
        {
          "key": "performance-contract",
          "title": "Profile and optimization design",
          "source_stages": [
            {
              "id": "profile",
              "primitive": "analyze"
            },
            {
              "id": "design",
              "primitive": "design"
            }
          ],
          "assertions": [
            {
              "key": "baseline-defined",
              "statement": "A reproducible baseline and target metric define the optimization scope",
              "suggested_priority": "P0",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        },
        {
          "key": "measured-improvement",
          "title": "Optimization benchmark and validation",
          "source_stages": [
            {
              "id": "optimize",
              "primitive": "implement"
            },
            {
              "id": "benchmark",
              "primitive": "test"
            },
            {
              "id": "validate",
              "primitive": "validate"
            }
          ],
          "assertions": [
            {
              "key": "target-achieved",
              "statement": "Measured performance meets the approved target without functional regression",
              "suggested_priority": "P0",
              "verify": {
                "mode": "metric",
                "template": "performance_target_met == true and regression_count == 0"
              }
            }
          ]
        }
      ]
    },
    {
      "registry_schema_version": "3.0",
      "seed_schema_version": "1.0",
      "source": {
        "kind": "composition",
        "name": "security-audit",
        "path": "workflow-system/agent/templates/registry.yaml",
        "schema_version": "2.0"
      },
      "name": "security-audit",
      "category": "composite",
      "tags": [
        "security",
        "audit",
        "vulnerability",
        "CVE",
        "scan"
      ],
      "description": "Threat modeling, scanning, analysis, remediation, and verification.",
      "seed_path": "workflow-system/agent/templates/seeds/security-audit.yaml",
      "partitions": [
        {
          "key": "threat-model",
          "title": "Threat model",
          "source_stages": [
            {
              "id": "threat_model",
              "primitive": "research"
            }
          ],
          "assertions": [
            {
              "key": "boundaries-covered",
              "statement": "Every in-scope trust boundary has an owner and documented abuse paths",
              "suggested_priority": "P0",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        },
        {
          "key": "scan-analysis",
          "title": "Security scan and codegraph analysis",
          "source_stages": [
            {
              "id": "scan",
              "primitive": "analyze"
            },
            {
              "id": "analyze",
              "primitive": "analyze"
            }
          ],
          "assertions": [
            {
              "key": "attack-surface-covered",
              "statement": "Approved scans and codegraph-assisted attack-surface analysis report zero untriaged critical findings",
              "suggested_priority": "P0",
              "verify": {
                "mode": "metric",
                "template": "untriaged_critical_findings == 0"
              }
            }
          ]
        },
        {
          "key": "remediation",
          "title": "Remediation and verification",
          "source_stages": [
            {
              "id": "remediate",
              "primitive": "implement"
            },
            {
              "id": "verify",
              "primitive": "validate"
            }
          ],
          "assertions": [
            {
              "key": "criticals-resolved",
              "statement": "Every confirmed critical finding is remediated or explicitly accepted by the user",
              "suggested_priority": "P0",
              "verify": {
                "mode": "metric",
                "template": "open_critical_findings == 0"
              }
            }
          ]
        }
      ]
    },
    {
      "registry_schema_version": "3.0",
      "seed_schema_version": "1.0",
      "source": {
        "kind": "composition",
        "name": "research-design-review-refine",
        "path": "workflow-system/agent/templates/registry.yaml",
        "schema_version": "2.0"
      },
      "name": "research-design-review-refine",
      "category": "composite",
      "tags": [
        "research",
        "design",
        "review",
        "refine",
        "iterate"
      ],
      "description": "Iterative research, design, review, refinement, and knowledge-gap closure.",
      "seed_path": "workflow-system/agent/templates/seeds/research-design-review-refine.yaml",
      "partitions": [
        {
          "key": "initial-design",
          "title": "Research and design",
          "source_stages": [
            {
              "id": "research",
              "primitive": "research"
            },
            {
              "id": "design",
              "primitive": "design"
            }
          ],
          "assertions": [
            {
              "key": "design-evidenced",
              "statement": "The design traces decisions and trade-offs to research evidence",
              "suggested_priority": "P1",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        },
        {
          "key": "refinement",
          "title": "Review and refinement",
          "source_stages": [
            {
              "id": "review",
              "primitive": "review"
            },
            {
              "id": "refine",
              "primitive": "refine"
            },
            {
              "id": "knowledge_gap_research",
              "primitive": "research"
            }
          ],
          "assertions": [
            {
              "key": "gaps-closed",
              "statement": "Review blockers and discovered knowledge gaps are resolved or explicitly deferred",
              "suggested_priority": "P0",
              "verify": {
                "mode": "metric",
                "template": "unresolved_review_blockers == 0"
              }
            }
          ]
        }
      ]
    },
    {
      "registry_schema_version": "3.0",
      "seed_schema_version": "1.0",
      "source": {
        "kind": "composition",
        "name": "dependency-setup",
        "path": "workflow-system/agent/templates/registry.yaml",
        "schema_version": "2.0"
      },
      "name": "dependency-setup",
      "category": "build",
      "tags": [
        "setup",
        "install",
        "dependency",
        "environment",
        "tooling",
        "configuration"
      ],
      "description": "Environment and tooling setup with bounded verification.",
      "seed_path": "workflow-system/agent/templates/seeds/dependency-setup.yaml",
      "partitions": [
        {
          "key": "setup-plan",
          "title": "Dependency research and plan",
          "source_stages": [
            {
              "id": "research",
              "primitive": "research"
            },
            {
              "id": "plan",
              "primitive": "plan"
            }
          ],
          "assertions": [
            {
              "key": "compatibility-known",
              "statement": "Versions, platform constraints, permissions, and rollback steps are documented",
              "suggested_priority": "P1",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        },
        {
          "key": "configuration",
          "title": "Configuration and verification",
          "source_stages": [
            {
              "id": "configure",
              "primitive": "implement"
            },
            {
              "id": "verify",
              "primitive": "test"
            }
          ],
          "assertions": [
            {
              "key": "setup-reproducible",
              "statement": "The configured environment is reproducible and passes its approved smoke verification",
              "suggested_priority": "P0",
              "verify": {
                "mode": "metric",
                "template": "setup_smoke_failures == 0"
              }
            }
          ]
        }
      ]
    },
    {
      "registry_schema_version": "3.0",
      "seed_schema_version": "1.0",
      "source": {
        "kind": "composition",
        "name": "onboarding",
        "path": "workflow-system/agent/templates/registry.yaml",
        "schema_version": "2.0"
      },
      "name": "onboarding",
      "category": "discover",
      "tags": [
        "onboarding",
        "setup",
        "getting-started",
        "contributor",
        "codebase"
      ],
      "description": "Contributor onboarding through analysis, documentation, setup, and verification.",
      "seed_path": "workflow-system/agent/templates/seeds/onboarding.yaml",
      "partitions": [
        {
          "key": "codebase-orientation",
          "title": "Codebase orientation",
          "source_stages": [
            {
              "id": "analyze",
              "primitive": "analyze"
            },
            {
              "id": "document",
              "primitive": "implement"
            }
          ],
          "assertions": [
            {
              "key": "entry-points-documented",
              "statement": "Key entry points, architecture, and contributor paths are documented using codegraph when available",
              "suggested_priority": "P1",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        },
        {
          "key": "contributor-setup",
          "title": "Contributor setup and verification",
          "source_stages": [
            {
              "id": "setup",
              "primitive": "implement"
            },
            {
              "id": "verify",
              "primitive": "test"
            }
          ],
          "assertions": [
            {
              "key": "first-run-green",
              "statement": "A new contributor can reproduce setup and pass the documented first-run checks",
              "suggested_priority": "P0",
              "verify": {
                "mode": "metric",
                "template": "onboarding_smoke_failures == 0"
              }
            }
          ]
        }
      ]
    },
    {
      "registry_schema_version": "3.0",
      "seed_schema_version": "1.0",
      "source": {
        "kind": "composition",
        "name": "demo-showcase",
        "path": "workflow-system/agent/templates/registry.yaml",
        "schema_version": "2.0"
      },
      "name": "demo-showcase",
      "category": "composite",
      "tags": [
        "demo",
        "showcase",
        "presentation",
        "prototype",
        "ui",
        "visual",
        "pitch"
      ],
      "description": "Demo and presentation decomposition with visual-quality evidence.",
      "seed_path": "workflow-system/agent/templates/seeds/demo-showcase.yaml",
      "partitions": [
        {
          "key": "narrative",
          "title": "Demo research and design",
          "source_stages": [
            {
              "id": "research",
              "primitive": "research"
            },
            {
              "id": "design",
              "primitive": "design"
            }
          ],
          "assertions": [
            {
              "key": "story-audience-fit",
              "statement": "The demo narrative and visual direction match the target audience and evidence",
              "suggested_priority": "P1",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        },
        {
          "key": "showcase",
          "title": "Build, review, refinement, and package",
          "source_stages": [
            {
              "id": "build",
              "primitive": "implement"
            },
            {
              "id": "review",
              "primitive": "review"
            },
            {
              "id": "refine",
              "primitive": "refine"
            },
            {
              "id": "package",
              "primitive": "release"
            }
          ],
          "assertions": [
            {
              "key": "showcase-ready",
              "statement": "Critical presentation flows pass review and the distributable package reproduces them",
              "suggested_priority": "P0",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        }
      ]
    },
    {
      "registry_schema_version": "3.0",
      "seed_schema_version": "1.0",
      "source": {
        "kind": "composition",
        "name": "product-verification",
        "path": "workflow-system/agent/templates/registry.yaml",
        "schema_version": "2.0"
      },
      "name": "product-verification",
      "category": "composite",
      "tags": [
        "verify",
        "visual",
        "acceptance",
        "interaction",
        "accessibility",
        "uat",
        "e2e",
        "product",
        "quality"
      ],
      "description": "User-facing verification across visual, interaction, accessibility, and acceptance axes.",
      "seed_path": "workflow-system/agent/templates/seeds/product-verification.yaml",
      "partitions": [
        {
          "key": "verification-design",
          "title": "Verification preconditions and design",
          "source_stages": [
            {
              "id": "precondition",
              "primitive": "implement"
            },
            {
              "id": "analyze",
              "primitive": "analyze"
            },
            {
              "id": "design_tests",
              "primitive": "design"
            }
          ],
          "assertions": [
            {
              "key": "coverage-designed",
              "statement": "Codegraph-informed flows cover visual, interaction, accessibility, and acceptance risks; ui-pro absence has an explicit degraded path",
              "suggested_priority": "P0",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        },
        {
          "key": "execution",
          "title": "Test implementation and execution",
          "source_stages": [
            {
              "id": "implement_tests",
              "primitive": "implement"
            },
            {
              "id": "execute_dev_tests",
              "primitive": "test"
            },
            {
              "id": "execute_verification",
              "primitive": "verify"
            }
          ],
          "assertions": [
            {
              "key": "axes-pass",
              "statement": "All four user-facing quality axes satisfy their approved thresholds",
              "suggested_priority": "P0",
              "verify": {
                "mode": "metric",
                "template": "visual_pass and interaction_pass and accessibility_pass and acceptance_pass"
              }
            }
          ]
        },
        {
          "key": "result-convergence",
          "title": "Review, refinement, and validation",
          "source_stages": [
            {
              "id": "review_results",
              "primitive": "review"
            },
            {
              "id": "refine",
              "primitive": "refine"
            },
            {
              "id": "validate",
              "primitive": "validate"
            }
          ],
          "assertions": [
            {
              "key": "findings-closed",
              "statement": "Verification findings are resolved and final readiness has zero blockers",
              "suggested_priority": "P0",
              "verify": {
                "mode": "metric",
                "template": "verification_blockers == 0"
              }
            }
          ]
        }
      ]
    },
    {
      "registry_schema_version": "3.0",
      "seed_schema_version": "1.0",
      "source": {
        "kind": "composition",
        "name": "entropy-cleanup",
        "path": "workflow-system/agent/templates/registry.yaml",
        "schema_version": "2.0"
      },
      "name": "entropy-cleanup",
      "category": "control",
      "tags": [
        "entropy",
        "gc",
        "cleanup",
        "freshness",
        "drift",
        "maintenance",
        "meta",
        "documentation"
      ],
      "description": "Stale-documentation and drift cleanup knowledge.",
      "seed_path": "workflow-system/agent/templates/seeds/entropy-cleanup.yaml",
      "partitions": [
        {
          "key": "drift-inventory",
          "title": "Drift scan and proposal",
          "source_stages": [
            {
              "id": "scan",
              "primitive": "analyze"
            },
            {
              "id": "propose",
              "primitive": "design"
            }
          ],
          "assertions": [
            {
              "key": "findings-classified",
              "statement": "Stale, duplicate, and conflicting artifacts have evidence-backed proposed dispositions",
              "suggested_priority": "P1",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        },
        {
          "key": "cleanup",
          "title": "Cleanup review and application",
          "source_stages": [
            {
              "id": "review",
              "primitive": "review"
            },
            {
              "id": "apply",
              "primitive": "implement"
            }
          ],
          "assertions": [
            {
              "key": "drift-reduced",
              "statement": "Approved cleanup removes targeted drift without deleting active contracts or immutable history",
              "suggested_priority": "P0",
              "verify": {
                "mode": "metric",
                "template": "remaining_targeted_drift == 0"
              }
            }
          ]
        }
      ]
    },
    {
      "registry_schema_version": "3.0",
      "seed_schema_version": "1.0",
      "source": {
        "kind": "template",
        "name": "migration",
        "path": "workflow-system/agent/templates/builtin/migration.yaml",
        "schema_version": "1.0"
      },
      "name": "migration",
      "category": "build",
      "tags": [
        "migrate",
        "upgrade",
        "transition",
        "port"
      ],
      "description": "Systematic migration with validation, cutover, and rollback readiness.",
      "seed_path": "workflow-system/agent/templates/seeds/migration.yaml",
      "partitions": [
        {
          "key": "assessment",
          "title": "Migration assessment and plan",
          "source_stages": [
            {
              "id": "assessment",
              "primitive": "analyze"
            },
            {
              "id": "plan",
              "primitive": "plan"
            }
          ],
          "assertions": [
            {
              "key": "risks-planned",
              "statement": "Dependencies, migration risks, cutover criteria, and rollback strategy are documented",
              "suggested_priority": "P0",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        },
        {
          "key": "implementation",
          "title": "Migration implementation",
          "source_stages": [
            {
              "id": "implement",
              "primitive": "implement"
            }
          ],
          "assertions": [
            {
              "key": "scope-migrated",
              "statement": "Every in-scope component is migrated without unapproved compatibility loss",
              "suggested_priority": "P0",
              "verify": {
                "mode": "metric",
                "template": "unmigrated_in_scope_components == 0"
              }
            }
          ]
        },
        {
          "key": "cutover",
          "title": "Validation and cutover",
          "source_stages": [
            {
              "id": "validate",
              "primitive": "validate"
            },
            {
              "id": "cutover",
              "primitive": "deploy"
            }
          ],
          "assertions": [
            {
              "key": "rollback-ready",
              "statement": "Integrity and functionality pass before cutover, with rollback readiness confirmed",
              "suggested_priority": "P0",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        }
      ]
    },
    {
      "registry_schema_version": "3.0",
      "seed_schema_version": "1.0",
      "source": {
        "kind": "template",
        "name": "skill-optimization",
        "path": "workflow-system/agent/templates/builtin/skill-optimization.yaml",
        "schema_version": "1.0"
      },
      "name": "skill-optimization",
      "category": "composite",
      "tags": [
        "skill",
        "optimize",
        "benchmark",
        "context",
        "compress",
        "iterate",
        "density"
      ],
      "description": "Agent-skill profiling, optimization, validation, and documentation knowledge.",
      "seed_path": "workflow-system/agent/templates/seeds/skill-optimization.yaml",
      "partitions": [
        {
          "key": "baseline",
          "title": "Skill survey and profile",
          "source_stages": [
            {
              "id": "survey",
              "primitive": "research"
            },
            {
              "id": "profile",
              "primitive": "analyze"
            }
          ],
          "assertions": [
            {
              "key": "baseline-measured",
              "statement": "Optimization targets have measured relevance, density, and context baselines",
              "suggested_priority": "P1",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        },
        {
          "key": "optimization",
          "title": "Optimization and quality gates",
          "source_stages": [
            {
              "id": "optimize",
              "primitive": "implement"
            },
            {
              "id": "si_chip_dogfood",
              "primitive": "validate"
            },
            {
              "id": "benchmark",
              "primitive": "test"
            }
          ],
          "assertions": [
            {
              "key": "candidate-improves",
              "statement": "The candidate clears the 0.10 iteration delta, has no regressions, and retains eighty percent coverage",
              "suggested_priority": "P0",
              "verify": {
                "mode": "metric",
                "template": "iteration_delta >= 0.10 and regression_count == 0 and coverage_pct >= 80"
              }
            }
          ]
        },
        {
          "key": "documentation",
          "title": "Optimization record",
          "source_stages": [
            {
              "id": "document",
              "primitive": "release"
            }
          ],
          "assertions": [
            {
              "key": "results-recorded",
              "statement": "Measured results and approved changes are recorded for future comparison",
              "suggested_priority": "P1",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        }
      ]
    },
    {
      "registry_schema_version": "3.0",
      "seed_schema_version": "1.0",
      "source": {
        "kind": "template",
        "name": "self-update",
        "path": "workflow-system/agent/templates/builtin/self-update.yaml",
        "schema_version": "1.0"
      },
      "name": "self-update",
      "category": "control",
      "tags": [
        "self-update",
        "update",
        "upgrade",
        "refs",
        "validate",
        "meta"
      ],
      "description": "Reference dependency research, integration, testing, and evaluation knowledge.",
      "seed_path": "workflow-system/agent/templates/seeds/self-update.yaml",
      "partitions": [
        {
          "key": "reference-delta",
          "title": "Reference change analysis",
          "source_stages": [
            {
              "id": "check-refs",
              "primitive": "analyze"
            },
            {
              "id": "research-updates",
              "primitive": "research"
            },
            {
              "id": "decompose",
              "primitive": "design"
            }
          ],
          "assertions": [
            {
              "key": "deltas-actionable",
              "statement": "Every changed reference has an evidence-backed relevance verdict and disjoint integration scope",
              "suggested_priority": "P1",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        },
        {
          "key": "integration",
          "title": "Integration and verification",
          "source_stages": [
            {
              "id": "integrate",
              "primitive": "implement"
            },
            {
              "id": "si_chip_gate",
              "primitive": "validate"
            },
            {
              "id": "test",
              "primitive": "test"
            }
          ],
          "assertions": [
            {
              "key": "integration-green",
              "statement": "Approved changes pass tests, lint, coverage, and applicable iteration-delta checks",
              "suggested_priority": "P0",
              "verify": {
                "mode": "metric",
                "template": "test_failures == 0 and lint_errors == 0 and coverage_pct >= 80"
              }
            }
          ]
        },
        {
          "key": "evaluation",
          "title": "Self-improvement evaluation",
          "source_stages": [
            {
              "id": "self-improve",
              "primitive": "validate"
            },
            {
              "id": "evaluate",
              "primitive": "validate"
            }
          ],
          "assertions": [
            {
              "key": "verdicts-recorded",
              "statement": "Every candidate has a go or no-go verdict and reference state is updated",
              "suggested_priority": "P0",
              "verify": {
                "mode": "metric",
                "template": "unassigned_verdicts == 0"
              }
            }
          ]
        }
      ]
    },
    {
      "registry_schema_version": "3.0",
      "seed_schema_version": "1.0",
      "source": {
        "kind": "composition",
        "name": "nines-assisted",
        "path": "workflow-system/agent/templates/registry.yaml",
        "schema_version": "3.0"
      },
      "name": "nines-assisted",
      "category": "composite",
      "tags": [
        "harness",
        "evaluation",
        "analysis",
        "pipeline",
        "self-eval",
        "review",
        "assisted",
        "full"
      ],
      "description": "Built-in harness-backed historical research and iteration decomposition knowledge.",
      "seed_path": "workflow-system/agent/templates/seeds/nines-assisted.yaml",
      "partitions": [
        {
          "key": "assisted-discovery",
          "title": "Assisted discovery and design",
          "source_stages": [
            {
              "id": "precondition",
              "primitive": "implement"
            },
            {
              "id": "research",
              "primitive": "research"
            },
            {
              "id": "design",
              "primitive": "design"
            },
            {
              "id": "plan",
              "primitive": "plan"
            }
          ],
          "assertions": [
            {
              "key": "assistance-accounted",
              "statement": "Built-in harness evidence, findings, architecture, and implementation plan are explicitly recorded",
              "suggested_priority": "P1",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        },
        {
          "key": "delivery",
          "title": "Implementation convergence",
          "source_stages": [
            {
              "id": "impl",
              "primitive": "implement"
            },
            {
              "id": "review",
              "primitive": "review"
            },
            {
              "id": "test",
              "primitive": "test"
            },
            {
              "id": "refine",
              "primitive": "refine"
            }
          ],
          "assertions": [
            {
              "key": "quality-converged",
              "statement": "Implementation passes review and tests with at least eighty percent coverage",
              "suggested_priority": "P0",
              "verify": {
                "mode": "metric",
                "template": "review_blockers == 0 and coverage_pct >= 80"
              }
            }
          ]
        },
        {
          "key": "release-readiness",
          "title": "Validation and release",
          "source_stages": [
            {
              "id": "validate",
              "primitive": "validate"
            },
            {
              "id": "release",
              "primitive": "release"
            }
          ],
          "assertions": [
            {
              "key": "release-approved",
              "statement": "Validation passes all criteria and release has explicit human approval",
              "suggested_priority": "P0",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        }
      ]
    },
    {
      "registry_schema_version": "3.0",
      "seed_schema_version": "1.0",
      "source": {
        "kind": "template",
        "name": "repo-init",
        "path": "workflow-system/agent/templates/builtin/repo-init.yaml",
        "schema_version": "1.0"
      },
      "name": "repo-init",
      "category": "discover",
      "tags": [
        "init",
        "scaffold",
        "bootstrap",
        "repo",
        "workspace",
        "rules"
      ],
      "description": "Repository workspace and governance initialization knowledge.",
      "seed_path": "workflow-system/agent/templates/seeds/repo-init.yaml",
      "partitions": [
        {
          "key": "repository-analysis",
          "title": "Repository analysis",
          "source_stages": [
            {
              "id": "analyze",
              "primitive": "analyze"
            }
          ],
          "assertions": [
            {
              "key": "environment-known",
              "statement": "Languages, build commands, AI tooling, and codegraph availability are recorded with explicit degraded behavior",
              "suggested_priority": "P0",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        },
        {
          "key": "workspace-scaffold",
          "title": "Workspace and rule scaffold",
          "source_stages": [
            {
              "id": "scaffold",
              "primitive": "implement"
            },
            {
              "id": "compile",
              "primitive": "implement"
            }
          ],
          "assertions": [
            {
              "key": "canonical-manifest",
              "statement": "All eight canonical workspace paths exist and rule outputs compile without drift",
              "suggested_priority": "P0",
              "verify": {
                "mode": "metric",
                "template": "canonical_paths_present == 8 and rule_drift_count == 0"
              }
            }
          ]
        },
        {
          "key": "operator-fit",
          "title": "Operator fit and verification",
          "source_stages": [
            {
              "id": "interview",
              "primitive": "analyze"
            },
            {
              "id": "verify",
              "primitive": "verify"
            }
          ],
          "assertions": [
            {
              "key": "initialization-verified",
              "statement": "Requested initialization depth completes and degraded optional tooling is reported without fabricated success",
              "suggested_priority": "P1",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        }
      ]
    },
    {
      "registry_schema_version": "3.0",
      "seed_schema_version": "1.0",
      "source": {
        "kind": "template",
        "name": "change-driven",
        "path": "workflow-system/agent/templates/builtin/change-driven.yaml",
        "schema_version": "1.0"
      },
      "name": "change-driven",
      "category": "composite",
      "tags": [
        "change",
        "propose",
        "preflight",
        "round",
        "archive",
        "lifecycle",
        "agent-workspace",
        "opsx"
      ],
      "description": "The sole executable checklist-round lifecycle runtime.",
      "seed_path": "workflow-system/agent/templates/seeds/change-driven.yaml",
      "partitions": [
        {
          "key": "proposal",
          "title": "Change proposal",
          "source_stages": [
            {
              "id": "propose",
              "primitive": "design"
            }
          ],
          "assertions": [
            {
              "key": "contract-anchored",
              "statement": "Goal, scope, and acceptance assertions are anchored with the user",
              "suggested_priority": "P0",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        },
        {
          "key": "execution",
          "title": "Change execution and verification",
          "source_stages": [
            {
              "id": "apply",
              "primitive": "implement"
            },
            {
              "id": "verify",
              "primitive": "verify"
            }
          ],
          "assertions": [
            {
              "key": "evidence-complete",
              "statement": "Every completed assertion has valid evidence and zero unresolved blockers",
              "suggested_priority": "P0",
              "verify": {
                "mode": "metric",
                "template": "evidence_coverage == 1.0 and blocker_count == 0"
              }
            }
          ]
        },
        {
          "key": "archive",
          "title": "Guarded archive",
          "source_stages": [
            {
              "id": "archive",
              "primitive": "deploy"
            }
          ],
          "assertions": [
            {
              "key": "archive-ready",
              "statement": "All acceptance assertions pass before source truth or archive state changes",
              "suggested_priority": "P0",
              "verify": {
                "mode": "metric",
                "template": "acceptance_pass_rate == 1.0"
              }
            }
          ]
        }
      ],
      "runtime_path": "workflow-system/agent/templates/builtin/change-driven.yaml"
    },
    {
      "registry_schema_version": "3.0",
      "seed_schema_version": "1.0",
      "source": {
        "kind": "template",
        "name": "web-design",
        "path": "workflow-system/agent/templates/builtin/web-design.yaml",
        "schema_version": "1.0"
      },
      "name": "web-design",
      "category": "composite",
      "tags": [
        "web-design",
        "frontend",
        "landing-page",
        "ui",
        "design",
        "polish",
        "impeccable",
        "ui-pro"
      ],
      "description": "Frontend design, implementation, refinement, and deterministic verification knowledge.",
      "seed_path": "workflow-system/agent/templates/seeds/web-design.yaml",
      "partitions": [
        {
          "key": "visual-system",
          "title": "Visual system and implementation",
          "source_stages": [
            {
              "id": "design",
              "primitive": "design"
            },
            {
              "id": "implement",
              "primitive": "implement"
            }
          ],
          "assertions": [
            {
              "key": "design-realized",
              "statement": "The implemented interface follows the approved ui-pro visual system across responsive breakpoints",
              "suggested_priority": "P0",
              "verify": {
                "mode": "manual"
              }
            }
          ]
        },
        {
          "key": "deterministic-refinement",
          "title": "Impeccable refinement and verification",
          "source_stages": [
            {
              "id": "refine",
              "primitive": "refine"
            },
            {
              "id": "verify",
              "primitive": "verify"
            }
          ],
          "assertions": [
            {
              "key": "antipatterns-clear",
              "statement": "Impeccable refinement is applied when available and deterministic anti-pattern count is zero",
              "suggested_priority": "P0",
              "verify": {
                "mode": "metric",
                "template": "antipattern_count == 0"
              }
            }
          ]
        }
      ]
    }
  ]
}
);
