"""The two-layer compaction digest (v24.0.0).

Design ref: `.local/research/v24.0.0_design_adr.md` §10.

Layer one is a deterministic structural extract rendered from the mapping
ledger. It is fully reproducible, which is what lets lint detect a hand edit.

Layer two is optional agent narration. Its cost of admission is that every
claim carries a verbatim anchor — a quoted fragment plus the archived path it
came from — and lint resolves each anchor against the archived original. A
summary whose claims cannot be traced back to a source is exactly how the
document this domain replaces became untrustworthy.
"""

from __future__ import annotations

import re
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path

from devolaflow.workspace_compact.models import (
    DIGEST_MARKER,
    CompactError,
)
from devolaflow.workspace_ledger import (
    Finding,
    finding,
    render_rows_table,
    write_generated_view,
)


def _cell(value: object, limit: int = 88) -> str:
    """Render a one-line table cell that cannot break the surrounding table."""

    text = str(value).replace("|", "\\|").replace("\n", " ").strip()
    return text if len(text) <= limit else text[: limit - 1] + "…"


AGENT_SECTION_HEADING = "## Agent Summary (unverified narration)"
STRUCTURAL_SECTION_HEADING = "## Relocated Originals"

#: An anchor is `[[archived/path#L12]] "verbatim fragment"`.
ANCHOR_RE = re.compile(r"\[\[([^\]#]+)#L(\d+)\]\]\s*[\"“]([^\"”]+)[\"”]")


@dataclass(frozen=True)
class AnchorCheck:
    """The result of resolving one verbatim anchor against its source."""

    path: str
    line: int
    fragment: str
    resolved: bool
    detail: str


def render_digest(folder: Path, agent_section: str | None = None) -> str:
    """Render the digest from the mapping ledger plus optional narration."""

    from devolaflow.workspace_compact.engine import load_mappings

    return render_digest_rows(load_mappings(folder), agent_section)


def render_digest_rows(
    rows: Sequence[Mapping[str, object]], agent_section: str | None = None
) -> str:
    """Render a digest from ledger rows, whether or not they are on disk yet.

    Splitting this out lets `plan` price the digest it *would* write by
    rendering it, rather than approximating its size with a constant that
    would drift the first time the layout changed.
    """

    total_tokens = sum(int(row.get("tokens_estimated", 0) or 0) for row in rows)
    total_bytes = sum(int(row.get("bytes", 0) or 0) for row in rows)
    lines = [
        DIGEST_MARKER,
        "# Compaction Digest",
        "",
        "Generated from `mappings.yaml`, which is append-only and authoritative.",
        "Nothing here was deleted: every row below names where the original now",
        "lives and the hash that proves it is unchanged. Use `devola-compact",
        "locate` to search the archived originals. Do not edit this file.",
        "",
        f"Relocated: {len(rows)} · Bytes: {total_bytes} · Tokens relocated: {total_tokens}",
        "",
        STRUCTURAL_SECTION_HEADING,
        "",
    ]
    if rows:
        lines.extend(
            render_rows_table(
                ("Seq", "Subject", "Original", "Archived at", "Tokens", "sha256"),
                [
                    (
                        str(row["sequence"]),
                        _cell(row.get("summary") or row.get("reason", "")),
                        f"`{row['source']}`",
                        f"`{row['destination']}`",
                        str(row.get("tokens_estimated", "")),
                        f"`{str(row.get('sha256', ''))[:12]}`",
                    )
                    for row in rows
                ],
            )
        )
    else:
        lines.append("Nothing has been relocated yet.")
    lines.append("")
    if agent_section:
        lines.extend(
            [
                AGENT_SECTION_HEADING,
                "",
                "Authored by an agent, not derived from the ledger. Every claim",
                "below carries a verbatim anchor; lint resolves each one against",
                "the archived original.",
                "",
                agent_section.strip(),
                "",
            ]
        )
    return "\n".join(lines).rstrip("\n") + "\n"


def estimate_digest_tokens(entries: Sequence[object]) -> int:
    """Price the digest a plan would write, in tokens.

    Compaction is not free: it deletes nothing and adds an index, so a small
    move can cost more than it saves. The v24 dogfood run relocated 432
    tokens and spent nearly all of them on the digest. Pricing the digest
    here is what lets `plan` say so before the operator approves.
    """

    from devolaflow.harness.context_tokens import estimate_text_tokens

    rows = [
        {
            "sequence": index,
            "source": getattr(entry, "source", ""),
            "destination": getattr(entry, "destination", ""),
            "tokens_estimated": getattr(entry, "tokens_estimated", 0),
            "bytes": getattr(entry, "bytes", 0),
            "sha256": getattr(entry, "sha256", ""),
            "summary": getattr(entry, "summary", ""),
            "reason": getattr(entry, "reason", ""),
        }
        for index, entry in enumerate(entries, 1)
    ]
    return estimate_text_tokens(render_digest_rows(rows)) or 0


def extract_agent_section(text: str) -> str | None:
    """Return the agent narration from an existing digest, if any."""

    if AGENT_SECTION_HEADING not in text:
        return None
    tail = text.split(AGENT_SECTION_HEADING, 1)[1]
    body = tail.split("\n\n", 4)
    return body[-1].strip() or None


def check_anchors(folder: Path, agent_section: str) -> tuple[AnchorCheck, ...]:
    """Resolve every verbatim anchor in a narration against its source."""

    checks: list[AnchorCheck] = []
    for match in ANCHOR_RE.finditer(agent_section):
        relative, line_text, fragment = match.group(1), match.group(2), match.group(3)
        path = folder / relative
        line_number = int(line_text)
        if not path.is_file():
            checks.append(
                AnchorCheck(relative, line_number, fragment, False, "archived source is missing")
            )
            continue
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except (OSError, UnicodeError) as exc:
            checks.append(AnchorCheck(relative, line_number, fragment, False, str(exc)))
            continue
        if not 1 <= line_number <= len(lines):
            checks.append(
                AnchorCheck(relative, line_number, fragment, False, "line is out of range")
            )
            continue
        if fragment.strip() not in lines[line_number - 1]:
            checks.append(
                AnchorCheck(
                    relative, line_number, fragment, False, "fragment is not present on that line"
                )
            )
            continue
        checks.append(AnchorCheck(relative, line_number, fragment, True, "resolved"))
    return tuple(checks)


def unanchored_claims(agent_section: str) -> tuple[str, ...]:
    """Return narration bullets that carry no verbatim anchor."""

    offenders: list[str] = []
    for raw in agent_section.splitlines():
        line = raw.strip()
        if not line.startswith(("-", "*")):
            continue
        if not ANCHOR_RE.search(line):
            offenders.append(line[:120])
    return tuple(offenders)


def write_digest(folder: Path, agent_section: str | None = None) -> tuple[str, ...]:
    """Re-render and persist the digest, preserving existing narration.

    Returns human-readable findings; an empty tuple means the digest is
    current and every anchor in its narration resolves.

    A narration problem is reported but does not stop the table from being
    re-rendered. The table is derived from the append-only ledger, so holding
    it back over agent prose leaves the authoritative rows unlisted — which is
    the failure the digest exists to prevent. The narration itself is written
    through unchanged: it is operator content, and silently dropping it would
    destroy the very claims the findings are asking someone to look at.
    """

    from devolaflow.workspace_compact.engine import digest_path

    target = digest_path(folder)
    narration = agent_section
    if narration is None and target.exists():
        try:
            narration = extract_agent_section(target.read_text(encoding="utf-8"))
        except (OSError, UnicodeError):
            narration = None
    findings: list[str] = []
    if narration:
        for orphan in unanchored_claims(narration):
            findings.append(f"UNANCHORED_CLAIM: {orphan}")
        for check in check_anchors(folder, narration):
            if not check.resolved:
                findings.append(f"BROKEN_ANCHOR: {check.path}#L{check.line}: {check.detail}")
    view_findings: tuple[Finding, ...] = write_generated_view(
        folder,
        target,
        render_digest(folder, narration),
        marker=DIGEST_MARKER,
    )
    findings.extend(f"{item.code}: {item.message}" for item in view_findings)
    return tuple(findings)


def audit_digest(folder: Path) -> tuple[Finding, ...]:
    """Report drift between the digest and its authoritative ledger."""

    from devolaflow.workspace_compact.engine import digest_path

    target = digest_path(folder)
    if not target.exists():
        return ()
    try:
        text = target.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as exc:
        return (finding("UNREADABLE_DIGEST", str(exc)),)
    if not text.startswith(DIGEST_MARKER):
        return (finding("HUMAN_DIGEST", "DIGEST.md is not a generated file"),)
    narration = extract_agent_section(text)
    findings: list[Finding] = []
    if narration:
        for orphan in unanchored_claims(narration):
            findings.append(finding("UNANCHORED_CLAIM", orphan))
        for check in check_anchors(folder, narration):
            if not check.resolved:
                findings.append(
                    finding("BROKEN_ANCHOR", f"{check.path}#L{check.line}: {check.detail}")
                )
    expected = render_digest(folder, narration)
    if text != expected:
        findings.append(finding("DIGEST_DRIFT", "DIGEST.md does not match mappings.yaml"))
    return tuple(findings)


def set_agent_section(folder: Path, agent_section: str) -> tuple[str, ...]:
    """Replace the narration, refusing any claim without a resolvable anchor."""

    if not agent_section.strip():
        raise CompactError("agent summary must not be empty")
    return write_digest(folder, agent_section)


__all__ = [
    "AGENT_SECTION_HEADING",
    "ANCHOR_RE",
    "STRUCTURAL_SECTION_HEADING",
    "AnchorCheck",
    "audit_digest",
    "check_anchors",
    "estimate_digest_tokens",
    "extract_agent_section",
    "render_digest",
    "render_digest_rows",
    "set_agent_section",
    "unanchored_claims",
    "write_digest",
]
