#!/usr/bin/env bash
# DevolaFlow host-bridge boundary hook (copilot).
# Generated by `python -m devolaflow.hostbridge install copilot` — do not hand-edit.
# Copilot command hooks are fail-closed; this wrapper normalizes all internal
# failures to an explicit allow response and exit 0.

if [ "$DEVOLAFLOW_HOST_ENFORCE" != "1" ]; then
  printf '%s\n' '{"permissionDecision":"allow"}'
  exit 0
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

if [ -x "$REPO_ROOT/.venv/bin/python" ]; then
  PY="$REPO_ROOT/.venv/bin/python"
elif command -v python3 >/dev/null 2>&1; then
  PY="python3"
else
  printf '%s\n' '{"permissionDecision":"allow"}'
  exit 0
fi

cd "$REPO_ROOT" || {
  printf '%s\n' '{"permissionDecision":"allow"}'
  exit 0
}

response="$("$PY" -m devolaflow.hostbridge --host copilot 2>/dev/null)"
status=$?
if [ "$status" -ne 0 ] || [ -z "$response" ]; then
  printf '%s\n' '{"permissionDecision":"allow"}'
else
  printf '%s\n' "$response"
fi
exit 0
