"""Gate quality mechanism — scoring, profiles, reports, convergence.

Design ref: design_decomposition_gate.md §5
"""

from devolaflow.gate.budget import (
    BREAK_UTILIZATION_THRESHOLD,
    WARN_UTILIZATION_THRESHOLD,
    TokenBudgetBreaker,
    from_profile_name,
)
from devolaflow.gate.convergence import (
    compute_trend,
    detect_ratchet_escalation,
    detect_stagnation,
    record_round_with_ratchet,
)
from devolaflow.gate.cycle_detector import (
    EDIT_OSCILLATION_MIN_LEN,
    EXACT_MATCH_CRITICAL_RUN,
    EXACT_MATCH_MIN_RUN,
    FUZZY_MATCH_MIN_WINDOW,
    MIN_HISTORY_FOR_DETECTION,
    CycleDetector,
)
from devolaflow.gate.models import (
    CYCLE_DEFAULT_SEVERITY,
    GATE_TYPE_ALIASES,
    LADDER_RUNG_NAMES,
    LADDER_RUNG_ORDER,
    AcceptanceCriterionResult,
    ArtifactSnapshot,
    BudgetAction,
    BudgetDecision,
    BudgetRecommendation,
    CheckResult,
    ConvergenceRound,
    CycleReport,
    CycleType,
    Finding,
    GateInput,
    GateProfile,
    GateType,
    GateVerdict,
    LadderEvaluation,
    LadderRung,
    LadderRungStatus,
    RatchetAction,
    StateSnapshot,
)
from devolaflow.gate.profiles import AUDIT, PROFILES, RELAXED, STANDARD, STRICT
from devolaflow.gate.ratchet import (
    DEFAULT_MAX_REGRESSIONS,
    DEFAULT_REGRESSION_TOLERANCE,
    ORACLE_WEIGHT_BUILD,
    ORACLE_WEIGHT_LINT,
    ORACLE_WEIGHT_TEST,
    MonotonicRatchet,
    RatchetLogEntry,
    compute_deterministic_oracle_score,
    hash_payload,
)
from devolaflow.gate.reinforcement import (
    MAX_REINFORCEMENT_RULES,
    ReinforcementBlock,
    ReinforcementRule,
    cycle_to_instruction,
    findings_to_reinforcement,
    merge_reinforcement_into_dispatch,
    reinforcement_to_dict,
)
from devolaflow.gate.reporter import generate_markdown_report, generate_yaml_report
from devolaflow.gate.scorer import (
    ARS_DIMENSION_WEIGHTS,
    DEFAULT_DIMENSION_WEIGHTS,
    SEVERITY_WEIGHTS,
    composite_score,
    evaluate_gate,
    evaluate_ladder,
    quality_score,
    run_gate_cli,
    score_acceptance_readiness,
)

__all__ = [
    "ARS_DIMENSION_WEIGHTS",
    "AUDIT",
    "AcceptanceCriterionResult",
    "ArtifactSnapshot",
    "BREAK_UTILIZATION_THRESHOLD",
    "BudgetAction",
    "BudgetDecision",
    "BudgetRecommendation",
    "CYCLE_DEFAULT_SEVERITY",
    "CycleDetector",
    "CycleReport",
    "CycleType",
    "DEFAULT_DIMENSION_WEIGHTS",
    "DEFAULT_MAX_REGRESSIONS",
    "DEFAULT_REGRESSION_TOLERANCE",
    "EDIT_OSCILLATION_MIN_LEN",
    "EXACT_MATCH_CRITICAL_RUN",
    "EXACT_MATCH_MIN_RUN",
    "FUZZY_MATCH_MIN_WINDOW",
    "GATE_TYPE_ALIASES",
    "LADDER_RUNG_NAMES",
    "LADDER_RUNG_ORDER",
    "MAX_REINFORCEMENT_RULES",
    "MIN_HISTORY_FOR_DETECTION",
    "MonotonicRatchet",
    "ORACLE_WEIGHT_BUILD",
    "ORACLE_WEIGHT_LINT",
    "ORACLE_WEIGHT_TEST",
    "PROFILES",
    "RELAXED",
    "RatchetAction",
    "RatchetLogEntry",
    "ReinforcementBlock",
    "ReinforcementRule",
    "SEVERITY_WEIGHTS",
    "STANDARD",
    "STRICT",
    "StateSnapshot",
    "TokenBudgetBreaker",
    "WARN_UTILIZATION_THRESHOLD",
    "CheckResult",
    "ConvergenceRound",
    "Finding",
    "GateInput",
    "GateProfile",
    "GateType",
    "GateVerdict",
    "LadderEvaluation",
    "LadderRung",
    "LadderRungStatus",
    "composite_score",
    "compute_deterministic_oracle_score",
    "compute_trend",
    "cycle_to_instruction",
    "detect_ratchet_escalation",
    "detect_stagnation",
    "evaluate_gate",
    "evaluate_ladder",
    "findings_to_reinforcement",
    "from_profile_name",
    "generate_markdown_report",
    "generate_yaml_report",
    "hash_payload",
    "merge_reinforcement_into_dispatch",
    "quality_score",
    "record_round_with_ratchet",
    "reinforcement_to_dict",
    "run_gate_cli",
    "score_acceptance_readiness",
]
