#!/usr/bin/env python3
"""v8.5.0 PV-05 (W-19 archive mechanism) — copy cycle research artifacts to docs/cycle-archive/.

W-19 codifies that after a MAJOR or MINOR cycle ships, the
``.local/research/<cycle-prefix>*`` artifacts are committed into
``docs/cycle-archive/<cycle-version>/`` so future cycle-N+1 SI-1
planning gates + external reviewers + new contributors can read the
design history without depending on ``.local/`` (gitignored on most
clones).

Usage::

    python scripts/archive_research_artifacts.py 9.0.0
    python scripts/archive_research_artifacts.py 9.0.0 --dry-run

The script is idempotent — re-running it is a no-op when the
destination already exists (no overwrites). Per the W-19 spec, the
archive is created at cycle CLOSE (after the final patch of a MINOR
series ships); calling mid-cycle is supported for incremental
checkpoints.

Output structure (per cycle)::

    docs/cycle-archive/v<MAJOR>.<MINOR>.0/
    ├── README.md             # auto-generated index
    ├── gap_analysis.md       # copy of v<MAJOR>.<MINOR>.0_gap_analysis.md
    ├── implementation_plan.md
    ├── design/               # copy of v<MAJOR>.<MINOR>.0_pv*_design.md
    ├── nines/                # copy of v<MAJOR>.<MINOR>.*_nines.{json,md}
    ├── evaluation/           # copy of v<MAJOR>.<MINOR>.*_evaluation.md
    └── retrospective.md      # copy of v<MAJOR>.<MINOR>.0_retrospective.md
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

SEMVER_RE = re.compile(r"^\d+\.\d+\.\d+$")


def _find_root() -> Path:
    p = Path(__file__).resolve().parent
    while p != p.parent:
        if (p / "pyproject.toml").exists():
            return p
        p = p.parent
    return Path.cwd()


def _cycle_prefix(version: str) -> str:
    """Return the prefix used to match research artifacts for a cycle.

    For ``9.0.0`` returns ``"v9.0."`` — captures every patch in the
    ``v9.0.X`` line (the cycle the MINOR version starts).
    """
    major_minor = ".".join(version.split(".")[:2])
    return f"v{major_minor}."


def _copy_one(src: Path, dst: Path, *, dry_run: bool) -> str:
    """Copy *src* to *dst* with idempotent semantics. Returns status string."""
    if dst.exists():
        return f"  EXISTS  {dst.relative_to(_find_root())}"
    if dry_run:
        return f"  WOULD   {dst.relative_to(_find_root())} <- {src.relative_to(_find_root())}"
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)
    return f"  COPIED  {dst.relative_to(_find_root())}"


def _gather_artifacts(research_dir: Path, prefix: str) -> dict[str, list[Path]]:
    """Categorize research files by W-19 archive bucket."""
    files = sorted(research_dir.glob(f"{prefix}*"))
    buckets: dict[str, list[Path]] = {
        "gap_analysis": [],
        "implementation_plan": [],
        "design": [],
        "nines": [],
        "evaluation": [],
        "retrospective": [],
        "other": [],
    }
    for f in files:
        if not f.is_file():
            continue
        name = f.name
        if "gap_analysis" in name:
            buckets["gap_analysis"].append(f)
        elif "implementation_plan" in name or "patch_plan" in name:
            buckets["implementation_plan"].append(f)
        elif "design" in name:
            buckets["design"].append(f)
        elif "nines" in name:
            buckets["nines"].append(f)
        elif "evaluation" in name or "evobench" in name.lower():
            buckets["evaluation"].append(f)
        elif "retrospective" in name:
            buckets["retrospective"].append(f)
        else:
            buckets["other"].append(f)
    return buckets


def _write_readme(archive_dir: Path, cycle_version: str, buckets: dict[str, list[Path]],
                  *, dry_run: bool) -> str:
    """Author the auto-generated index README at archive root."""
    readme_path = archive_dir / "README.md"
    if readme_path.exists():
        return f"  EXISTS  {readme_path.relative_to(_find_root())}"

    lines = [
        f"# Cycle Archive — v{cycle_version}",
        "",
        f"Auto-generated by `scripts/archive_research_artifacts.py` per Workflow",
        f"Rule W-19. Mirrors the `.local/research/v{cycle_version[:3]}*` artifacts so",
        "future cycle-N+1 planning gates can reference cycle-N research without",
        "depending on `.local/` (which is gitignored on most clones).",
        "",
        "## Contents",
        "",
    ]
    for bucket, files in buckets.items():
        if not files:
            continue
        lines.append(f"### {bucket}")
        lines.append("")
        for f in files:
            lines.append(f"* `{f.name}`")
        lines.append("")
    lines.append("## Cross-references")
    lines.append("")
    lines.append(f"* `CHANGELOG.md` `## [{cycle_version}]` — release note")
    lines.append(f"* `.local/research/` — live research workspace (gitignored)")
    lines.append("* `AGENTS.md` §W-19 — archive policy")
    lines.append("")

    if dry_run:
        return f"  WOULD   {readme_path.relative_to(_find_root())} (README.md)"

    readme_path.parent.mkdir(parents=True, exist_ok=True)
    readme_path.write_text("\n".join(lines), encoding="utf-8")
    return f"  COPIED  {readme_path.relative_to(_find_root())}"


def archive(cycle_version: str, *, dry_run: bool = False) -> int:
    """Archive .local/research/<prefix>* into docs/cycle-archive/v<cycle>/."""
    root = _find_root()
    research_dir = root / ".local" / "research"
    if not research_dir.is_dir():
        print(f"ERROR: {research_dir} does not exist — nothing to archive")
        return 1

    prefix = _cycle_prefix(cycle_version)
    archive_dir = root / "docs" / "cycle-archive" / f"v{cycle_version}"

    print(f"Archiving cycle v{cycle_version}")
    print(f"  source: {research_dir.relative_to(root)} (prefix '{prefix}')")
    print(f"  dest:   {archive_dir.relative_to(root)}")
    if dry_run:
        print("  (dry run — no files will be copied)\n")
    else:
        archive_dir.mkdir(parents=True, exist_ok=True)
        print()

    buckets = _gather_artifacts(research_dir, prefix)
    if not any(buckets.values()):
        print(f"  WARN: no research artifacts found matching '{prefix}*'")
        return 0

    print(_write_readme(archive_dir, cycle_version, buckets, dry_run=dry_run))

    bucket_to_subdir = {
        "gap_analysis": archive_dir,
        "implementation_plan": archive_dir,
        "design": archive_dir / "design",
        "nines": archive_dir / "nines",
        "evaluation": archive_dir / "evaluation",
        "retrospective": archive_dir,
        "other": archive_dir / "other",
    }

    total_copied = 0
    for bucket, files in buckets.items():
        if not files:
            continue
        subdir = bucket_to_subdir[bucket]
        for src in files:
            dst = subdir / src.name
            status = _copy_one(src, dst, dry_run=dry_run)
            print(status)
            if "COPIED" in status or "WOULD" in status:
                total_copied += 1

    print(f"\n{total_copied} file(s) {'would be ' if dry_run else ''}copied to {archive_dir.relative_to(root)}.")
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("version", help="cycle version to archive (e.g. 9.0.0)")
    parser.add_argument("--dry-run", action="store_true", help="show planned copies without writing")
    args = parser.parse_args()

    if not SEMVER_RE.match(args.version):
        print(f"Error: '{args.version}' is not a valid semver (expected X.Y.Z)")
        sys.exit(1)

    sys.exit(archive(args.version, dry_run=args.dry_run))


if __name__ == "__main__":
    main()
