#!/usr/bin/env bash
# DevolaFlow session-start resume hook (cursor).
# Generated by `python -m devolaflow.hostbridge install cursor` — do not hand-edit.
# Read-only: prints a resume summary for context injection; every error
# path degrades to empty output + exit 0.

# R5 strict fast path: workspace engagement off -> silent, no Python.
if [ "$DEVOLAFLOW_AGENT_WORKSPACE" != "1" ]; then
  exit 0
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

if [ -x "$REPO_ROOT/.venv/bin/python" ]; then
  PY="$REPO_ROOT/.venv/bin/python"
elif command -v python3 >/dev/null 2>&1; then
  PY="python3"
else
  # No interpreter available -> no context injected.
  exit 0
fi

cd "$REPO_ROOT" || exit 0
exec "$PY" -m devolaflow.hostbridge resume --host cursor
